# Generated by Django 5.2.17 on 2026-09-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_roles_and_schools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='school',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
