# Generated by Django 5.2.17 on 2026-09-08 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصف')),
                ('grade', models.CharField(max_length=80, verbose_name='المرحلة أو الصف الدراسي')),
                ('subject', models.CharField(max_length=80, verbose_name='المادة')),
                ('academic_year', models.CharField(max_length=20, verbose_name='العام الدراسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='accounts.teacherprofile', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'صف',
                'verbose_name_plural': 'الصفوف',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_code', models.CharField(help_text='رمز غير حساس يستخدم أثناء التحليل بدل اسم الطالب.', max_length=24, verbose_name='الرمز الداخلي')),
                ('display_name', models.CharField(blank=True, help_text='يبقى داخل نظام بيّن ولا يرسل إلى مزود الذكاء الاصطناعي.', max_length=120, verbose_name='اسم العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='classrooms.classroom', verbose_name='الصف')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
                'ordering': ('internal_code',),
            },
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('teacher', 'name', 'academic_year'), name='unique_classroom_per_teacher_year'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('classroom', 'internal_code'), name='unique_student_code_per_classroom'),
        ),
    ]
