# Generated by Django 5.2.17 on 2026-09-09 12:29

import apps.assessments.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_school_delete_school'),
        ('assessments', '0002_submission_submissionanswer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.assessments.models.attachment_upload_path, verbose_name='الملف')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(verbose_name='حجم الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to='accounts.userprofile', verbose_name='رفع بواسطة')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assessments.submission', verbose_name='التسليم')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ('created_at',),
            },
        ),
    ]
