# Generated by Django 5.2.17 on 2026-09-09 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_submissionattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentOcrResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'جاري الاستخراج'), ('completed', 'مكتمل'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('extracted_text', models.TextField(blank=True, verbose_name='النص المستخرج')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_result', to='assessments.submissionattachment', verbose_name='المرفق')),
            ],
            options={
                'verbose_name': 'نتيجة التعرف الضوئي',
                'verbose_name_plural': 'نتائج التعرف الضوئي',
            },
        ),
    ]
