# Generated by Django 5.2.17 on 2026-09-10 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_attachmentocrresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrAnswerCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extracted_text', models.TextField(blank=True, verbose_name='النص المقترح')),
                ('source', models.CharField(default='ocr', max_length=20, verbose_name='المصدر')),
                ('status', models.CharField(choices=[('suggested', 'مقترح'), ('confirmed', 'مؤكد')], default='suggested', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_candidates', to='assessments.question', verbose_name='السؤال')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_candidates', to='assessments.submission', verbose_name='التسليم')),
            ],
            options={
                'verbose_name': 'اقتراح إجابة',
                'verbose_name_plural': 'اقتراحات الإجابات',
                'ordering': ('question__order',),
                'constraints': [models.UniqueConstraint(fields=('submission', 'question'), name='unique_ocr_candidate_per_question_and_submission')],
            },
        ),
    ]
