# Generated by Django 5.2.17 on 2026-09-10 09:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_ocranswercandidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('correct', 'صحيح'), ('partial', 'صحيح جزئيًا'), ('incorrect', 'غير صحيح')], max_length=20, verbose_name='الحالة')),
                ('awarded_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='الدرجة الممنوحة')),
                ('feedback', models.TextField(verbose_name='الملاحظات')),
                ('misconception', models.TextField(blank=True, verbose_name='الفهم الخاطئ')),
                ('model_name', models.CharField(max_length=80, verbose_name='النموذج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('evaluated_at', models.DateTimeField(verbose_name='تاريخ التقييم')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='assessments.submissionanswer', verbose_name='الإجابة')),
            ],
            options={
                'verbose_name': 'تقييم إجابة',
                'verbose_name_plural': 'تقييمات الإجابات',
                'constraints': [models.CheckConstraint(condition=models.Q(('awarded_score__gte', 0)), name='evaluation_awarded_score_is_not_negative')],
            },
        ),
    ]
