# Generated by Django 5.2.17 on 2026-09-10 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_answerevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.CharField(choices=[('foundation', 'تأسيس'), ('practice', 'تدريب'), ('ready', 'جاهز')], max_length=20, verbose_name='المجموعة')),
                ('status', models.CharField(choices=[('pending', 'قيد الإنشاء'), ('completed', 'مكتملة'), ('failed', 'فشلت')], default='pending', max_length=20, verbose_name='الحالة')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='العنوان')),
                ('summary', models.TextField(blank=True, verbose_name='الملخص')),
                ('objectives', models.JSONField(default=list, verbose_name='الأهداف')),
                ('activities', models.JSONField(default=list, verbose_name='الأنشطة')),
                ('teacher_guidance', models.TextField(blank=True, verbose_name='إرشادات المعلم')),
                ('model_name', models.CharField(blank=True, max_length=80, verbose_name='النموذج')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوليد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_plans', to='assessments.assessment', verbose_name='الاختبار')),
            ],
            options={
                'verbose_name': 'خطة علاجية',
                'verbose_name_plural': 'الخطط العلاجية',
                'constraints': [models.UniqueConstraint(fields=('assessment', 'group'), name='unique_remediation_plan_per_assessment_group')],
            },
        ),
    ]
