# Generated by Django 5.2.17 on 2026-09-10 13:40

import apps.assessments.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_school_delete_school'),
        ('assessments', '0007_remediationplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSourceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.assessments.models.source_attachment_upload_path, verbose_name='الملف')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('content_type', models.CharField(max_length=100, verbose_name='نوع الملف')),
                ('file_size', models.PositiveIntegerField(verbose_name='حجم الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_attachments', to='assessments.assessment', verbose_name='الاختبار')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_source_attachments', to='accounts.userprofile', verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'ورقة اختبار',
                'verbose_name_plural': 'أوراق الاختبار',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(verbose_name='الترتيب')),
                ('extracted_text', models.TextField(verbose_name='النص المستخرج')),
                ('proposed_max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة المقترحة')),
                ('proposed_model_answer', models.TextField(blank=True, verbose_name='الإجابة النموذجية المقترحة')),
                ('status', models.CharField(choices=[('suggested', 'مقترح'), ('confirmed', 'مؤكد')], default='suggested', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_candidates', to='assessments.assessment', verbose_name='الاختبار')),
            ],
            options={
                'verbose_name': 'سؤال مستخرج',
                'verbose_name_plural': 'الأسئلة المستخرجة',
                'ordering': ('order',),
                'constraints': [
                    models.UniqueConstraint(fields=('assessment', 'order'), name='unique_question_candidate_order_per_assessment'),
                ],
            },
        ),
    ]
